"""
This type stub file was generated by pyright.
"""

class AstronomicalCalculations:
    GEOMETRIC_ZENITH = ...
    def __init__(self) -> None:
        ...
    
    def elevation_adjustment(self, elevation: float) -> float:
        ...
    
    def adjusted_zenith(self, zenith: float, elevation: float) -> float:
        ...
    


