"""
This type stub file was generated by pyright.
"""

from datetime import datetime
from typing import Optional
from dateutil import tz
from zmanim.util.math_helper import MathHelper

class GeoLocation(MathHelper):
    def __init__(self, name: str, latitude: float, longitude: float, time_zone, elevation: Optional[float] = ...) -> None:
        ...
    
    @property
    def latitude(self) -> float:
        ...
    
    @latitude.setter
    def latitude(self, latitude): # -> None:
        ...
    
    @property
    def longitude(self) -> float:
        ...
    
    @longitude.setter
    def longitude(self, longitude): # -> None:
        ...
    
    @property
    def time_zone(self) -> tz.tzfile:
        ...
    
    @time_zone.setter
    def time_zone(self, time_zone): # -> None:
        ...
    
    @property
    def elevation(self) -> float:
        ...
    
    @elevation.setter
    def elevation(self, elevation): # -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    @classmethod
    def GMT(cls): # -> Self@GeoLocation:
        ...
    
    def antimeridian_adjustment(self) -> int:
        ...
    
    def local_mean_time_offset(self) -> float:
        ...
    
    def standard_time_offset(self) -> int:
        ...
    
    def time_zone_offset_at(self, utc_time: datetime) -> float:
        ...
    


