"""
This type stub file was generated by pyright.
"""

from datetime import date
from typing import Optional
from zmanim.util.astronomical_calculations import AstronomicalCalculations
from zmanim.util.geo_location import GeoLocation

class NOAACalculator(AstronomicalCalculations):
    JULIAN_DAY_JAN_1_2000 = ...
    JULIAN_DAYS_PER_CENTURY = ...
    @staticmethod
    def name(): # -> Literal['US National Oceanic and Atmospheric Administration Algorithm']:
        ...
    
    def utc_sunrise(self, target_date: date, geo_location: GeoLocation, zenith: float, adjust_for_elevation: bool = ...) -> Optional[float]:
        ...
    
    def utc_sunset(self, target_date: date, geo_location: GeoLocation, zenith: float, adjust_for_elevation: bool = ...) -> Optional[float]:
        ...
    


