"""
This type stub file was generated by pyright.
"""

from datetime import datetime
from typing import Optional
from zmanim.hebrew_calendar.jewish_date import JewishDate

class JewishCalendar(JewishDate):
    SIGNIFICANT_DAYS = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def significant_day(self) -> Optional[str]:
        ...
    
    def is_assur_bemelacha(self) -> bool:
        ...
    
    def is_tomorrow_assur_bemelacha(self) -> bool:
        ...
    
    def has_candle_lighting(self) -> bool:
        ...
    
    def has_delayed_candle_lighting(self) -> bool:
        ...
    
    def is_yom_tov(self) -> bool:
        ...
    
    def is_yom_tov_assur_bemelacha(self) -> bool:
        ...
    
    def is_erev_yom_tov(self) -> bool:
        ...
    
    def is_yom_tov_sheni(self) -> bool:
        ...
    
    def is_erev_yom_tov_sheni(self) -> bool:
        ...
    
    def is_chol_hamoed(self) -> bool:
        ...
    
    def is_taanis(self) -> bool:
        ...
    
    def is_rosh_chodesh(self) -> bool:
        ...
    
    def is_erev_rosh_chodesh(self) -> bool:
        ...
    
    def is_chanukah(self) -> bool:
        ...
    
    def day_of_chanukah(self) -> Optional[int]:
        ...
    
    def day_of_omer(self) -> Optional[int]:
        ...
    
    def molad_as_datetime(self) -> datetime:
        ...
    
    def techilas_zman_kiddush_levana_3_days(self) -> datetime:
        ...
    
    def techilas_zman_kiddush_levana_7_days(self) -> datetime:
        ...
    
    def sof_zman_kiddush_levana_between_moldos(self) -> datetime:
        ...
    
    def sof_zman_kiddush_levana_15_days(self) -> datetime:
        ...
    


